name: Publish Release to PyPI

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          cache: 'poetry'

      - uses: snok/install-poetry@v1
        with:
          version: 1.1.13

      - name: Publish to PyPI
        run: poetry publish --build --username __token__ --password ${{ secrets.PYPI_TOKEN }}
